# Please fill out the following fields to customize your documentation site
site_name: Project title
site_description: Project description
repo_url: https://github.com/organiztion/repo #for example https://github.com/Karpova-Lab/pyControl-D-Series-Breakout
repo_name: organization/repo #for example Karpova-Lab/pyControl-D-Series-Breakout
site_author: Jane Doe
copyright: Copyright &copy; 2024 Jane Doe

extra:
    discussion_url: # for example https://github.com/Karpova-Lab/pyControl-D-Series-Breakout/discussions
    issues_url: # for example https://github.com/Karpova-Lab/pyControl-D-Series-Breakout/issues/new
    version:
        provider: mike

nav:
    - Overview: index.md
    - Electronics: electronics.md
    - Hardware: hardware.md
    - Software: software.md

docs_dir: src
site_dir: ../docs

theme:
    name: material
    custom_dir: overrides
    logo: _home.svg
    palette:
        primary: teal
        accent: grean
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.footer
        - navigation.instant
        - content.code.copy

extra_css:
    - _extra.css

plugins:
    - search
    - include-markdown:
          comments: false

markdown_extensions:
    - toc:
          title: On this page
          permalink: "#"
          toc_depth: 3
    - admonition
    - attr_list
    - md_in_html
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.snippets:
          base_path: src
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
